### ISSUE TITLE
Compatability - 1Password 6 crashes when Cairo is active

### ISSUE THREAD

**Issue by owenworley** [cairoshell/cairoshell#154]
1Password 6 crashes on launch when Cairo is open.
Closing Cairo makes 1Password work again.

(https://1password.com/downloads/)

**Comment by dremin** [comment]
I am only able to reproduce this when explorer.exe is running in addition to Cairo. Are you seeing similar results?

Compatibility is difficult with non-open source software since I can't see their code, but I would suggest sending AgileBits Support your 1Password logs so that their app can be more resilient. Of course, I will look into whatever adjustments can be made within Cairo as well to improve this.

**Comment by owenworley** [comment]
Thanks, I will contact 1Password and ask them to look at a fix. 

Yes I only see the error when Cairo is not replacing Explorer.

I would love to use Cairo as main shell without explorer.exe, but due to other compatibility issues this is not feasible yet for my everyday work machine - I am looking forward to the day it is though.
