### ISSUE TITLE
Removing desktops

### ISSUE THREAD

**Issue by GR8smoky** [cairoshell/cairoshell#159]
Just discovered this shell, and have been experimenting with it.  In doing so, I have created some desktops that I would like to clear, delete, disable or whatever term to eliminate them is proper.  Short of reconfiguring the installation is there a way to accomplish this?
While I recognize this is a pre-release edition, I hope someone will kindly assist me.  I have been rather impressed so far.  Using under Win 10 without replacing file explorer.
Thank you.

**Comment by josuave** [comment]
Are you referencing the virtual desktop system built in the windows 10?

Sent from my iPhone

On Jun 15, 2018, at 9:06 PM, GR8smoky <notifications@github.com<mailto:notifications@github.com>> wrote:


Just discovered this shell, and have been experimenting with it. In doing so, I have created some desktops that I would like to clear, delete, disable or whatever term to eliminate them is proper. Short of reconfiguring the installation is there a way to accomplish this?
While I recognize this is a pre-release edition, I hope someone will kindly assist me. I have been rather impressed so far. Using under Win 10 without replacing file explorer.
Thank you.

**Comment by GR8smoky** [comment]
No.  I am referring to what I believe are called Dynamic Desktops.
In an attempt to explain clearly, in Cairo go to and click on Places on top menu bar, then select Downloads; this will load all folders from that directory on to your screen that can now be scrolled through with the dynamic navigation toolbar.  Can that individual screen/desktop be later cleared or removed from showing in Cairo without deleting the directory from the HD/file explorer/system?
Hope this clears up my question.
Thanks for responding.

**Comment by josuave** [comment]
I believe this is accomplished by clicking the home button on the dynamic desktop navigation

Sent from my iPhone

On Jun 16, 2018, at 11:30 AM, GR8smoky <notifications@github.com<mailto:notifications@github.com>> wrote:


No. I am referring to what I believe are called Dynamic Desktops.
In an attempt to explain clearly, in Cairo go to and click on Places on top menu bar, then select Downloads; this will load all folders from that directory on to your screen that can now be scrolled through with the dynamic navigation toolbar. Can that individual screen/desktop be later cleared or removed from showing in Cairo without deleting the directory from the HD/file explorer/system?
Hope this clears up my question.
Thanks for responding.

**Comment by GR8smoky** [comment]
No, that does not accomplish my goal, it just rotates the undesired "desktop" or screen out of view.
 
What I want to accomplish is to remove/delete the screen from Cairo's rotation scheme.  What has occurred is that in experimenting I did some things I would like to undo, and keep some other things (like the taskbar configuration), so as to not start from scratch again. Plus I know I will make errors and want to make changes again in the future.

I have played with options, key combos, and context screens to no avail so far.  Now wondering if there is a profile or configuration file that could be modified.

If any ideas or suggestions, I'd appreciate them.  Thanks for your help so far. Kind of late here so will not work on anything until tomorrow.

**Comment by dremin** [comment]
The only desktop that Cairo saves is the default one set in Cairo Settings. Are you talking about the back/forward buttons? The back button traverses up the directory structure, while the forward button traverses desktop history. However, this is not persisted across restarts of Cairo.

**Comment by josuave** [comment]
I think this is a misunderstanding of the functionality. The feature is the directory that the desktop polls to show the desktop icons can be changed. You are not creating multiple desktops, you are just changing where the desktop’s icons come from. Think of it like an explorer window.

Sent from my iPhone

On Jun 16, 2018, at 11:02 PM, GR8smoky <notifications@github.com<mailto:notifications@github.com>> wrote:


No, that does not accomplish my goal, it just rotates the undesired "desktop" or screen out of view.

What I want to accomplish is to remove/delete the screen from Cairo's rotation scheme. What has occurred is that in experimenting I did some things I would like to undo, and keep some other things (like the taskbar configuration), so as to not start from scratch again. Plus I know I will make errors and want to make changes again in the future.

I have played with options, key combos, and context screens to no avail so far. Now wondering if there is a profile or configuration file that could be modified.

If any ideas or suggestions, I'd appreciate them. Thanks for your help so far. Kind of late here so will not work on anything until tomorrow.

**Comment by josuave** [comment]
I think this is a feature request to be able to view and remove undesired Dynamic Desktop history. My recommendation for such a feature would be to either click and hold OR right click the Dynamic Desktop navigation to show a history menu. This menu would allow direct navigation to that entry on click and also have an [x] button to the right for removal. Since the Dynamic Desktop navigation can be moved around the  history menu would have to be location aware so that it’s not display off screen. On other request that comes to mind while discussing this is to have a configurable limit to the length of history that is stored  from one to ∞ ( or some other reasonable limit, I don’t have the source open and I don’t remember what I originally coded it as )

Sent from my iPhone

On Jun 17, 2018, at 1:13 AM, Sam Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


The only desktop that Cairo saves is the default one set in Cairo Settings. Are you talking about the back/forward buttons? The back button traverses up the directory structure, while the forward button traverses desktop history. However, this is not persisted across restarts of Cairo.

**Comment by josuave** [comment]
I added a proof of concept to my fork
https://github.com/josuave/cairoshell

Sent from my iPhone

On Jun 17, 2018, at 1:13 AM, Sam Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


The only desktop that Cairo saves is the default one set in Cairo Settings. Are you talking about the back/forward buttons? The back button traverses up the directory structure, while the forward button traverses desktop history. However, this is not persisted across restarts of Cairo.

**Comment by GR8smoky** [comment]
I think I am beginning to get things clearer.  
Per Dremin commit, it is the back button screens I'd like to erase -- just the screens not actually the directories or files themselves. Those back button screens do persist from close to restart (at least using windows as file manager).
Per josuave commit, if I follow correctly, I believe that addresses what I seek.  Have not been able to look at proof of concept, yet.
I do realize profile in user account does not have any bearing.
Thank you both.

**Comment by GR8smoky** [comment]
Just a final comment here.
Thanks for all your help. Looked at proof of concept, but way above my pay grade.
Sorry I can not be of more help in arriving at a solution.

**Comment by josuave** [comment]
That’s OK, I did notice a small bug in the WPF implementation of the Browse button’s context menu. In some cases I need to double right click to get the context menu opening function to react appropriately.

Sent from my iPhone
Jun 17, 2018, at 8:32 PM, GR8smoky <notifications@github.com<mailto:notifications@github.com>> wrote:


Just a final comment here.
Thanks for all your help. Looked at proof of concept, but way above my pay grade.
Sorry I can not be of more help in arriving at a solution.

—

On

**Comment by dremin** [comment]
@josuave - were you planning on finishing this in your fork?

**Comment by josuave** [comment]
I haven’t had much time lately to look at this. I’ll try to pull it back up this weekend and review. I need to add a remove button [x] to each menu item and I’m also not sure where the right click bug is coming from yet.

Sent from my iPhone

On Jun 27, 2018, at 10:38 PM, Sam Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


@josuave<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjosuave&data=02%7C01%7C%7C7f74c5ef6a4c493cd64b08d5dca02d92%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636657502865190827&sdata=qNwdl%2F2ebhm5wr3qgB9EbjXbDyIpaO2jDqIc07hHLeg%3D&reserved=0> - were you planning on finishing this in your fork?

**Comment by josuave** [comment]
Just for clarification: The bug is actually with the built-in contextmenu opening event.

Sent from my iPhone

On Jun 27, 2018, at 10:38 PM, Sam Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


@josuave<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjosuave&data=02%7C01%7C%7C7f74c5ef6a4c493cd64b08d5dca02d92%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636657502865190827&sdata=qNwdl%2F2ebhm5wr3qgB9EbjXbDyIpaO2jDqIc07hHLeg%3D&reserved=0> - were you planning on finishing this in your fork?

**Comment by dremin** [comment]
@josuave is it possibly due to the toolbar not having focus on first right-click?

**Comment by josuave** [comment]
This is odd. It seems to be something. I’m thinking of removing the contextmenu on the button itself and on right click of the button show an standalone contextmenu that is not bound to any control. I left my dev laptop back home so I won’t be able to look again until this weekend.

Sent from my iPhone

On Jul 3, 2018, at 7:44 PM, Sam Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


@josuave<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjosuave&data=02%7C01%7C%7C0293b2c430684c01599608d5e13edd11%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636662582463674442&sdata=B71pCmPCbh8Dd0uYjMrtIIOdtP%2BfogUEv0%2FoCSMJA8c%3D&reserved=0> is it possibly due to the toolbar not having focus on first right-click?

**Comment by dremin** [comment]
The work done for this by @josuave will be available the next release.

**Comment by GR8smoky** [comment]
Thanks for head's up and all the work done on this issue
