### ISSUE TITLE
Additional menu bar customizability

### ISSUE THREAD

**Issue by dremin** [cairoshell/cairoshell#180]
As many things as possible should be customizable in the menu bar. Add the following options to Cairo Settings:

- Show/hide 'Places' menu
- Show/hide volume icon
- Show/hide 'Action Center' icon
- Show/hide clock
- Show/hide search icon

**Comment by josuave** [comment]
Should we investigate using plugins, for some of this, to add or remove functionality rather than toggles? This reminds me of my old days of using litestep or sharpe!

Sent from my iPhone

On Aug 9, 2018, at 12:15 AM, Sam Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


As many things as possible should be customizable in the menu bar. Add the following options to Cairo Settings:

  *   Show/hide 'Places' menu
  *   Show/hide volume icon
  *   Show/hide 'Action Center' icon
  *   Show/hide clock
  *   Show/hide search icon

**Comment by dremin** [comment]
Making everything plugins is a long term goal. Maybe it makes sense to use this as a beginning to further develop the plugin system.

**Comment by dremin** [comment]
@josuave The item here that is getting me hung up is that we can't render XAML in plugins which can have multiple instances rendered. For example, volume needs to show on all monitors.

**Comment by josuave** [comment]
I agree. The ability is there, prism for example. We will need to decide on the right path. I am, usually by choice, a back end coder so my xaml experience is lower than most. I will pull my dev machine back out and investigate some more. On a side note, I would also like a way for extensions to create settings. This should store all settings in same place, allow a settings pane, global vs user options... etc.

**Comment by dremin** [comment]
I agree, settings should be extensible, in a user-friendly way so that extensions which ship with Cairo can be configured without needing to know that they are extensions.

**Comment by dremin** [comment]
This is resolved in the latest release.
