### ISSUE TITLE
Few Feature request

### ISSUE THREAD

**Issue by jakkaas** [cairoshell/cairoshell#266]
1) option for Disable Cairo taskbar.
2) Autohide Cairo menu bar.
3) Switch position of Cairo menu bar.
4) Right-click dynamic desktop folder.
5) An Option of adding toolbar like Lenovo battery gauge etc in the menu bar.
6) Search bar in menu bar 
 Thanks

**Comment by josuave** [comment]
Forgive my briefness, I am in my phone in an airport.

1) option for Disable Cairo taskbar. 
- this is in settings already

2) Autohide Cairo menu bar. 
- this is a good feature request, please create a new issue using the feature request template 

3) Switch position of Cairo menu bar. 
- please elaborate? Top? Bottom ? Left or right?

4) Right-click dynamic desktop folder.
- please elaborate? I assume that you would want to right click a folder and make it the dynamic desktop’s path

5) An Option of adding toolbar like Lenovo battery gauge etc in the menu bar. 
- please elaborate? Are you asking for Cairo to host native Windows Taskbar “toolbars”. I think that the Lenovo stuff doesn’t even implement the standard toolbar functionality, I think it draws on top of explorer. 

6) Search bar in menu bar
- please elaborate? I assume that you want the search text entry to always be visible instead of having to click the magnifying glass

**Comment by jakkaas** [comment]
-option for Disable Cairo taskbar.
this is in settings already
A-**This setting hides Cairo taskbar but then shows window taskbar. I wanted the option of disabling Cairo taskbar without showing window taskbar. I.e no need of any taskbar.**


Autohide Cairo menu bar.
this is a good feature request, please create a new issue using the feature request template
Ans-**Sure**

Switch position of Cairo menu bar.
please elaborate? Top? Bottom ? Left or right?
Ans: **Anywhere either on Top, bottom, left or right**


Right-click dynamic desktop folder.
please elaborate? I assume that you would want to right click a folder and make it the dynamic desktop’s path
Ans: **No. I want the ability to open a dynamic desktop folder in explorer (probably by double-clicking) and/or right-click a dynamic desktop folder and get the context menu.**

An Option of adding toolbar like Lenovo battery gauge etc in the menu bar.
please elaborate? Are you asking for Cairo to host native Windows Taskbar “toolbars”. I think that the Lenovo stuff doesn’t even implement the standard toolbar functionality, I think it draws on top of explorer.
**A: I am not sure about this. But I want a widget/toolbar like what I have added a picture of. It basically shows the battery percentage. You could also show battery % indicator in Cairo menu bar without need of any other widget/toolbar.**
![image](https://user-images.githubusercontent.com/43289832/58743780-cd1fa300-8455-11e9-8050-46fd54feeacb.png)



Search bar in menu bar
please elaborate? I assume that you want the search text entry to always be visible instead of having to click the magnifying glass
Ans. **I wanted a option to search windows in Cairo menu. I thought I had seen a magnifying glass like option initially but I was not sure. Right now I don't have any magnifying glass like option visible on Cairo menu bar.**
![image](https://user-images.githubusercontent.com/43289832/58743823-79618980-8456-11e9-8f3b-5c090cc668d7.png)

Thanks

**Comment by josuave** [comment]
Are you still using Cairo? 
This is an older issue submission and I wanted to followup.
Are you using Explorer as shell or Cairo?

**Comment by jakkaas** [comment]
Sorry but I am not currently using cairo

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jakkaas** [comment]
I have started using Cairo again. Using explorer as shell

**Comment by dremin** [comment]
Going to close this because these are either non-actionable items or duplicate issues:
- To hide taskbar, use Cairo as shell and disable Cairo taskbar, then there is no explorer taskbar to show. Otherwise, enable autohide on the explorer taskbar.
- Autohide menu bar - #120 
- Bottom menu bar - #142 
- Battery in menu bar - we have implemented the battery icon, flyouts will be #54 and we added plugins support for additional features.
- Search in menu bar - not showing this icon means the Windows Search service is not running, if you enable that it should show up.
