### ISSUE TITLE
[QUESTION] What was the starting point for this project?

### ISSUE THREAD

**Issue by haydennyyy** [cairoshell/cairoshell#269]
I want to learn how to do this kind of thing, as it seems pretty cool. I know it's not a particularly easy thing to do (probably) but I'd like to have a look into it.

**Comment by josuave** [comment]
Well there are 2 starting points I guess, first the idea and second the development.

For me I wanted to modify the shell, push the limits, and create something original. Come up with an idea that fit a need, made a task easier, or just something cool.

Here is an article that has our original roots: 
https://www.google.com/amp/s/encontrei.wordpress.com/2008/02/09/cairo-windows-shell/amp/

As far as the development, a lot of research and testing. Since the Windows Shell source and process is not publicly documented the development of a functional replacement can get daunting. Luckily we have a few projects that we can reference, even though the development of them is stalled, I would recommend looking at litestep, geo shell, emerge desktop and others. https://en.m.wikipedia.org/wiki/List_of_alternative_shells_for_Windows

You will have to decide if you want to start your own project or contribute to another.

**Comment by haydennyyy** [comment]
Thanks! I was looking into starting a good tiling DM for Windows.

**Comment by josuave** [comment]
Like a window manager?

**Comment by haydennyyy** [comment]
Kind of, yeah. I've made a repo for it. Any advice would be well appreciated, if you have the time.
https://github.com/haydennyyy/i4wm
> Yes, that is a blatant ripoff name from i3.
