### ISSUE TITLE
Sideload with windows

### ISSUE THREAD

**Issue by sethnorton2000** [cairoshell/cairoshell#276]
Hi! I use cario to eliminate windows explorer so I can edit files for a game, but I don't want to fully run my pc on this software 24/7. Is there a way to keep cario installed but access it with a .exe when I need to load into it?
Thanks in advance!
-Seth Norton

**Comment by josuave** [comment]
While cairo is running do you want explorer running

Sent from my iPhone

On Aug 24, 2019, at 1:05 PM, sethnorton2000 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi! I use cario to eliminate windows explorer so I can edit files for a game, but I don't want to fully run my pc on this software 24/7. Is there a way to keep cario installed but access it with a .exe when I need to load into it?
Thanks in advance!
-Seth Norton

**Comment by sethnorton2000** [comment]
no, I use cario as the explorer

________________________________

**Comment by josuave** [comment]
What you would probably want to do is:
Kill explorer and then open cairo

**Comment by sethnorton2000** [comment]
Well how do I open cario? No .exe it creates when installed, in order to run it I have to run the entire installation process again

________________________________

**Comment by josuave** [comment]
Once installed it should be accessible, at anytime. Dont set it as shell

**Comment by sethnorton2000** [comment]
Gotcha, one more question. When I play overwatch while Cairo is open, it really seems to be eating my frames, I normally run at 300fps smoothly but when Cairo is open, I run at 120 or less, is there any optimization I can to do so it doesn’t take up as many frames?

________________________________

**Comment by josuave** [comment]
You can try turning off hardware rendering. That will eat cpu cycles instead of gpu. There is a setting for it in cairo

Sent from my iPhone

On Aug 24, 2019, at 3:57 PM, sethnorton2000 <notifications@github.com<mailto:notifications@github.com>> wrote:

Gotcha, one more question. When I play overwatch while Cairo is open, it really seems to be eating my frames, I normally run at 300fps smoothly but when Cairo is open, I run at 120 or less, is there any optimization I can to do so it doesn’t take up as many frames?

________________________________

**Comment by dremin** [comment]
Questions answered; closing. Feel free to re-open if this is incorrect!
