### ISSUE TITLE
In full screen mode, in Firefox and SMPlayer, Cairo stays on top

### ISSUE THREAD

**Issue by Handwrit** [cairoshell/cairoshell#30]
Obviously, it's good Cairo can stay on top most of the time, but sometimes I'd just like to watch a video fullscreen.

Thanks for Cairo, by the way! It's really great!!!!!!!

**Comment by dremin** [comment]
Interesting, I implemented support for hiding in full-screen in a previous release and it is working for me with Firefox. Does Cairo stay on top in every full-screen scenario for you, or are there situations where Cairo hides properly?

**Comment by Handwrit** [comment]
Chrome and Google Earth are no different, Cairo remains atop them in full screen mode.

I'm using Windows 10 Pro, (automatically, thanks MS!) updated to Creator's Edition. 

My videocard is the MSI Radeon RX 640. 

It should be added, I have not scrounged up the pennies to buy a Windows license, so perhaps that messes with draw order or something? However, I would think not, since it's Explorer that draws the Activate watermark, or so I thought.

**Comment by dremin** [comment]
I will try with an un-activated version of Windows to see if this triggers the problem. If not, I'll add some additional logging to Cairo so that we can track this down!

**Comment by mdmk** [comment]
@Handwrit you could try to extend your trial period if the OS is freshly installed.
See [(https://www.howtogeek.com/howto/windows-7/extend-the-windows-7-trial-from-30-to-120-days/)]
Never tried it myself but it seems possible to extend the trial period up to one year with a simple tweak:
https://www.techperiod.com/extend-windows-7-trial-period-for-one-year/

If it works for you then hopefully you can try without watermark to see if the issue is still there.

**Comment by dremin** [comment]
I have made an adjustment to this functionality in the latest build. You can update using 'Check for updates' in the Cairo menu. Please let me know if this helped the issue.

**Comment by dremin** [comment]
@Handwrit Is this still happening for you in the latest version?
