### ISSUE TITLE
Desktop Icons

### ISSUE THREAD

**Issue by nickisghosty** [cairoshell/cairoshell#33]
I've been checking back every few months waiting for windows 10 compatibility along with an over all smoother feel. I've got to say, I appreciate the work and open source-ness. Ever since I stumbled upon this project probably a little over a year ago now, I saw great potential, and wished it would work on my laptops. Now it does! I hope I can give you some constructive criticism, and hope that you don't take my feedback in the wrong way. Maybe once I get a little more free time and finish some projects I have started I'll be able to sift through the source and create a branch... Anyway, I noticed a problem with the desktop icons and the folder navigation overlapping, making finding files and folders difficult. I'm tempted to move everything out of the desktop folder so there are no icons for Cario's navigation to overlap. An easy fix to implement would to be to hide all of the desktop icons along with windows taskbar. Also a setting to chose between using your navigation or windows desktop would be nice. Another thing I noticed, or just might not have found out how to do yet is relocating the top menu, the active window bar, and the desktop navigation. First thing I tried doing when I saw the desktop navigator was dragging and dropping to a new location only to find out I couldn't, which then led me to right clicking on each bar to see if there is a setting to dock the panels on other edges. If there is a setting somewhere, please inform me of where, and consider making easier to find. I understand that this is a work in progress, so I didnt expect to see a great deal of customization yet, like changing colors, sizes, and what not, but would be a sweet feature to add. One other thing that I've noticed right away was the taskview button. I'm not sure if that is for Windows 10 multi tasking, because I currently only have a windows 8 machine avail. or if its a future feature to be added. But clicking it does nothing for me. Lastly, I have ran the app grabber after the install and it froze on finding apps, and showed a message to copy and paste the info into an issue but I exited it on accident before copying. So if there isn't already a log file which Im unaware of its whereabouts, it would be helpful to include one. Other than that, great job. Truely impressed if this is a project you've done all yourself, or if you've had other working on it, still impressed haha. If you need any help lmk, I've been getting a lot better at c#, i know javascript pretty well, and im pretty decent with graphics. Or even if you just need a monkey to test new features in the UI. I'll be using this as my default shell, so anything else I run into ill let you know.

**Comment by nickisghosty** [comment]
Also something you may want to add is a mostly transparent backdrop behind the desktop navigation icons, for readability and customization. and a hotkey or button on either the active window bar or menu bar to bring the navigation to front without having to minimize everything

**Comment by mdmk** [comment]
On my desktop, native icons are not hid anymore making them overlap with Cairo's own icons.
[Example of overlapping](https://user-images.githubusercontent.com/32496803/31349373-45bbb29c-ad23-11e7-971b-27f6e21c86d0.png)
The problem appears on my desktop but not on my laptop (both Win10 64bit).
If I right click on desktop to hide native icons it works but if I close Cairo native icons dont reappear as well.
I don't know if it is the same kind of overlapping than @nickisghosty, in his case it seems to be the top bar that is overlaped by the icons.

@dremin I think the [small bar](https://user-images.githubusercontent.com/32496803/31349671-6e4a2558-ad24-11e7-8430-4d7d65b92dca.png) to control the dynamic desktop is too visible and it feels not very nice (very subjective). Perhaps you could make it dim, so it shows when hovered by mouse but is hidden the rest of the time? Otherwise the feature is good, perhaps an optional button on this bar to replace dynamic desktop by native desktop (without reboot) would be good but not sure if it is worth the effort.

For me, the must have customizations would be:
- change bars position (top dock, but also left and right, and perhaps bottom navigation)
- change icon size in dock (too small for my taste and my eyes) and font size accordingly
- auto-hide dock
- completely hide windows taskbar (without requiring replacing explorer) and not only auto-hide
But again it is a work in progress, so we can wait a millestone or two I think

@nickisghosty talks about a backdrop, I think it could be a good idea
You should see what stardock does with [fences](https://user-images.githubusercontent.com/32496803/31350210-9aee02ee-ad26-11e7-8dc5-42c13adf6909.png) for inspiration

Visually it is almost that I think.
But the fences of stardock are kinds of visual groups that can be organized manually.
Perhaps a future feature to add to Cairo?

@dremin I confirm task view is not reliable, often doesn't work on Windows 10

I had the same problem with app grabber on previous releases on the previous repository.
The version on this repository is the first to work in my case.

**Comment by dremin** [comment]
@mdmk yikes, I changed how I hide the default desktop icons recently. Do you use a slideshow wallpaper on that machine? Also, could you try this slightly older build to see if it hides your icons properly? https://github.com/dremin/cairoshell/releases/tag/v0.2.6456

When you refer to a dock do you mean the bottom Cairo taskbar and quick launch? The Windows taskbar should be completely hidden and not on auto-hide, is yours set to auto-hide already by chance?

I will be back at my development machine in a few more days so hopefully I can get to work on some of these things very soon :)

**Comment by mdmk** [comment]
@dremin 
Yes I use a slideshow wallpaper on both machines (sames pictures for the most part).
Same problem with a single image (I did not reboot between changes).
I'll try this older build tomorrow, I will return feedback then.

My bad, yes by dock I mean the Cairo taskbar and quick lauch, which looks pretty much like a dock (except it is not possible to customize it alot, at least for now).
In fact, when the taskbar is completely hidden, the default behaviour seems wrong to me, there is a [blank space](https://user-images.githubusercontent.com/32496803/31357816-8f44a412-ad43-11e7-903c-70ed71048577.png) just the size of the not shown native taskbar.
So that space is lost.
I prefer to auto-hide, so that the space is reclaimed (except a one pixel high line I think)
Then, the native taskbar bothers me popping when I dont want so today I tried to hide it with a autohotkey script, it is ugly but it works and fixes my problem temporarily, it is definitely not an elegant nor satisfying solution.

OK, there is already a a fair amount of things to tackle ahah :)
I look forward to future milestones.

**Comment by nickisghosty** [comment]
Tried running the app grabber again, got the same error message pop up, and the app grabber stays on the Please wait finding apps screen, this time I got the error:

`Please submit a bug report with the error text below. Thanks! 

Message: The service did not respond to the start or control request in a timely fashion.

The service did not respond to the start or control request in a timely fashion.

Target Site: System.Collections.Generic.IEnumerable`1[Windows.ApplicationModel.Package] FindPackagesForUser(System.String)
Version: 0.2.6469.18805

   at Windows.Management.Deployment.PackageManager.FindPackagesForUser(String userSecurityId)
   at CairoDesktop.UWPInterop.StoreAppHelper.GetStoreApps()
   at CairoDesktop.AppGrabber.AppGrabber.getStoreApps()
   at CairoDesktop.AppGrabber.AppGrabber.GetApps()
   at CairoDesktop.AppGrabber.AppGrabber.get_ProgramList()
   at CairoDesktop.AppGrabber.AppGrabberUI.Window_ContentRendered(Object sender, EventArgs e)
   at System.Windows.Window.OnContentRendered(EventArgs e)
   at System.Windows.Window.<PostContentRendered>b__198_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Comment by nickisghosty** [comment]
Also, the desktop icon overlap i was talking about, heres a<a href="http://i68.tinypic.com/2i0cjte.png"> screenshot</a>

its only when the desktop setting is enabled. so when that is enabled there should be a line of code to hide the windows desktop icons.

**Comment by mdmk** [comment]
@dremin Same problem with the slightly older build.
The icons overlap in the same way.
With or without slideshow wallpaper.

**Comment by dremin** [comment]
@nickisghosty @mdmk I have just released a build with fixes to the issues listed here. You can update using 'Check for updates' in the Cairo menu. Please let me know if the fixes helped!

**Comment by nickisghosty** [comment]
NICE! My issues no longer exist. Much appreciated, will let you know if I bump into anything else and/or think of any important features.

**Comment by mdmk** [comment]
@dremin Check for updates works like a charm (automatically proposed at lauch).
Desktop icons overlap no more and the dynamic desktop bar is movable.

Don't know if this issue will be closed or not but it is a bit huge now, I made a summary of what have been said and done or not.

### Already implemented:

- [x] Possibility to disable dynamic desktop
- [x] Theme support

### Corrected by the latest build:

- [x] Desktop icons overlapping
- [x] Make the dynamic desktop bar movable
- [x] App grabber bug

### Remaining bugs:

- [ ] Taskview button not working reliably
- [ ] Reclaim native taskbar space

### Features to add:

- [ ] Moving taskbar and menu bar
- [ ] Add backdrop behind desktop incons
- [ ] Button and/or hotkey to bring bars to front
- [ ] Dim the dynamic desktop bar
- [ ] Rotate bars (90 degrees)
- [ ] Change icon size in taskbar

**Comment by dremin** [comment]
Regarding "Reclaim native taskbar space", try setting your Windows taskbar size to small icons, this removes the extra gap.

**Comment by nickisghosty** [comment]
well the question is, are you wanting that button to be used between versions of windows or just windows 10 multiple desktops? cause for it not to be a useless button on win 7 and 8 you could create an alt tab like screen. or you could create your own virtual desktop functionality for all three and nevermind the windows 10 taskview

**Comment by nickisghosty** [comment]
cool, a suggestion with that... since i don't like how there isn't a close 'x' on each window on windows versions prior to 10 would be to go with your own alt tab screen.. so when you click the button the list of windows stay up, along with also being able to customize to your liking, like adding a close 'x' to each window, or 3d shuffling, etc.

quick question.. do you code for work? or just a hobby? j/w

**Comment by mdmk** [comment]
@dremin Tried this. Gained some space actually.

But what I want to do is this:
![screenshot22](https://user-images.githubusercontent.com/32496803/31510077-ecb7d500-af83-11e7-9bdb-ec8d78a5435a.png)

And not this:
![screenshot23](https://user-images.githubusercontent.com/32496803/31510081-eea97bde-af83-11e7-956b-0c48df53b19e.png)

That is to say, make the taskbar overlap the bottom of the maximized windows.
Without autohide it is not that convenient, but if this feature is added it will be a welcome gain of space.

@nickisghosty Did you ever try [dexpot](http://www.dexpot.de/?lang=en) ? For OSs prior to Windows 10 it is a good/better replacement feature. You have to enable the "exposé"-like view for alt-tab. If I remember correctly there is crosses here.

**Comment by nickisghosty** [comment]
@mdmk I have not. Spent a good amount of time yesterday looking for a replacement but hadn't came across this one though, thanks.

@dremin Something that happened with the update... The custom folders I added to the top bar disappeared afterward-just fyi. No problem re-adding them.

**Comment by dremin** [comment]
Here's something to try for the Task View feature: Seems like it works if the Cairo notification area is disabled (and restarting Cairo afterwards) for me. Very strange..

**Comment by mdmk** [comment]
Tested it, I can confirm this.
Strange actually.

**Comment by dremin** [comment]
@nickisghosty I haven't seen that happen before. I would be interested if it happens again after the next update. Do you have a `%appdata%\CairoStacksConfig.xml` file?

**Comment by mdmk** [comment]
Yes.
[Here](https://gist.github.com/mdmk/adb56451be80a317b0a75ced67280a86) the content of the file.

**Comment by dremin** [comment]
Task View is working consistently in Windows 10 in today's build. For versions prior to 10, I am thinking of just hiding the button for now as there is no built in virtual desktop manager.

**Comment by mdmk** [comment]
@dremin I confirm this.
The native taskbar autohide also works well in multiscreen.
I updated the checklist higher in the thread.

Some design ideas:
I'd like to have a button for showing desktop. Why not propose something like a single button with left click taskview, rightclick show desktop? On versions prior to 10 it would be left or right click show desktop so the button stays here. But different behavior on different OS can also be a bad thing...
And multiclick buttons are complicated to memorize. But it is hard to add many more buttons to the taskbar and keep good readability.
By the way, the icon has too many stripes I think. I looks like the grip of a handle and I expected it to be draggable by mouse at first. It is very mainstream and not original but a simple three-stripe hamburger 
![screenshot34](https://user-images.githubusercontent.com/32496803/31583594-d5926dfa-b19e-11e7-9e37-c2767bfc5392.png) icon would suffice.

**Comment by dremin** [comment]
I closed this since the Task View issue is resolved, which is the last remaining issue from the original post. However, there were a lot of other suggestions in this thread, feel free to make separate issues for those! (note- I won't necessarily implement every suggestion, but I want to at least be able to address and track it!)
