### ISSUE TITLE
Notification Area disappears when disabling taskbar

### ISSUE THREAD

**Issue by kingfetty** [cairoshell/cairoshell#345]
**Summary**
When disabling the taskbar option in Cairo Desktop settings, the notification area is also removed completely from the Menu Bar.  This is despite the notification area being enabled in the Menu Bar settings. 

**Version:** 
0.3.6906.0 - Pre-release

**Expected behavior:**
Notification Area should operate independently of the taskbar.

**Comment by dremin** [comment]
I actually made an intentional change here to not show the notification area if the taskbar is disabled (but it still needs some follow-up adjustments).

It is disabled for a few reasons:
- If the taskbar is disabled, it is assumed the Explorer taskbar is visible, meaning the result would be multiple notification areas.
- When the Cairo notification area is enabled, the Explorer one stops receiving updates from applications, meaning they will operate inconsistently. Only allowing one notification area provides a more consistent experience.

However, there are some issues with this change that we need to resolve:
- Settings should make this clear.
- If Cairo is running as shell, we can't assume the Explorer taskbar is visible, so we should allow the notification area to show in this case.

**Comment by dremin** [comment]
The two items I mentioned above will be resolved in the next release. The Cairo notification area will still be intentionally hidden when the taskbar is disabled, but only when Explorer is shell.

**Comment by dremin** [comment]
The above items have been addressed in the latest release.
