### ISSUE TITLE
hiding title bar

### ISSUE THREAD

**Issue by sychris** [cairoshell/cairoshell#41]
So I've been using this for about a week now and by far the biggest issue I have is the launch bar covers windows title bar's that are maximized. making it very hard to close them also, windows often open at to top of the screen making it very hard to move them. further exasperated as the task bar offers minimize and restore but no move option there as well. I do know that as a workaround you can alt down right to get to a windows menu but not all programs support this.

Win 7 64bit
Cairo Desktop Environment Version 0.2.6497.4921 - Pre-release with Explorer disabled

just did a minor bit of searching and found this that might help
https://www.codeproject.com/Articles/6741/AppBar-using-C -the link says C but its C#
and
https://www.codeproject.com/KB/shell/csdoesshell3.aspx?fid=14729&select=1796941#xx1796941xx

**Comment by dremin** [comment]
Thanks for using Cairo! Thanks for details and mentioning that you have Explorer disabled. I have implemented AppBar support in Cairo, but AppBar requires Explorer to be enabled. Instead, Cairo is adjusting the system workarea when it is set as the shell, so that Cairo doesn't overlap windows.

I just tested having Cairo set as shell instead of Explorer, on Windows 7 x64, and it seems to be working properly.

A couple things to check:
- Is Cairo drawing a wallpaper? If not, Cairo isn't acting as shell and won't adjust the system workarea, and will try to use an Explorer AppBar instead.
- What is the value in the following registry key? `HKCU\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\Shell` Cairo will not act as an Explorer replacement unless "cairodesktop" is in this value somewhere.

Please let me know what you find regarding the two items above.

**Comment by sychris** [comment]
whoa didnt know about that appbar support only working with explorer... (makes sense) should have looked in to the code lol. as for the reg key "HKCU\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\Shell" in the Winlogon there is a shell key with "C:\Program Files\Cairo Shell\CairoDesktop.exe" as the value however there is also a folder in Winlogon named Shell with a default key and no value set... you probably want the first one but just in case.

HKLM still seams to be set as explorer.exe should i change this?

**Comment by dremin** [comment]
Interesting. Is Cairo properly loading your startup items on boot?

**Comment by sychris** [comment]
yep all startup items are working properly...  some system stuff is not ie sound mixer notification but i expect this is due to no explorer shell -ive replaced almost all of them a long time ago with other software so no biggie.

so lol i think i might know whats going on..  the reason i switched to cairo is because i have made extensive changes to my os one of which is some sort of DPI scaling which had resulted in my notification buttons to be shrank incredibly small... i've also shrank my title bars window padding and more. didn't even think about it till now but there's a good chance its having an effect on this program as well let me poke around a bit and see if i can find the culprit on my end.

**Comment by dremin** [comment]
I think you're on to something- I noticed I am not DPI scaling the workspace calculations properly, so there is a partial overlap. I'll get this fixed for the next build.

**Comment by dremin** [comment]
Could you please try the update I released today? This issue should now be resolved-- let me know if it isn't!
