### ISSUE TITLE
 Feature Request: Reclaim native taskbar space

### ISSUE THREAD

**Issue by mdmk** [cairoshell/cairoshell#42]
When hiding the native taskbar, the space is lost.
It would be good to adjust the workspace to benefit from this space.
Cairo taskbar would then be in front of the windows.

**Comment by dremin** [comment]
Cairo has an option to auto-hide the Windows taskbar in order to reclaim space left from it.

![capture](https://user-images.githubusercontent.com/7373633/31798253-a102104e-b500-11e7-8590-c4ed28711d55.PNG)

I will see if the system allows me to remove the taskbar as an 'app bar' to reclaim space without auto-hide.

**Comment by dremin** [comment]
After some experimenting and some research, I don't believe anything past the options provided is possible unless you select the option to replace Explorer when installing Cairo.
