### ISSUE TITLE
After install, can't type in explorer searchbox and also search. 

### ISSUE THREAD

**Issue by Blackrucat** [cairoshell/cairoshell#432]
After install Cairo Shell, I can't type in explorer searchbox and also search. 

**Expected behavior**
That I could write normally

**System information:**
 - Windows version:  10
 - Cairo version:  always the latest 
 - 32-bit or 64-bit: 64-bits
 - In Cairo Settings > Advanced, is Cairo set as shell?: yes

**Screenshots**

![image](https://user-images.githubusercontent.com/56588184/93962322-f8a45c00-fd30-11ea-8226-72ae0c078e0b.png)

**Comment by josuave** [comment]
This is due to Microsoft changing the search UI over to UWP/WinRT. Unfortunately, unless Microsoft makes it so that UWP/WinRT can run without Explorer running as shell, we wo not have any immediate fixes or workarounds.

Alternatively, you could attempt to use a third party file browser or Search provider.
