### ISSUE TITLE
bbad qa team josauve is not good

### ISSUE THREAD

**Issue by austinHeisleyCook** [cairoshell/cairoshell#443]
Main calculator is not accessible to users on windows due class not found or addec #436
Closed
austinHeisleyCook opened this issue 2 days ago · 6 comments 
this is not ok you must fix or will expose this project bug

**Comment by dremin** [comment]
UWP/WinRT apps are not supported when running a shell other than Explorer. If you would like to use these apps, we recommend running Cairo with the default option to run alongside Explorer rather than replacing it as shell. You can change this setting in Cairo Settings > Advanced. We have reported this problem to Microsoft; only they can resolve this.
