### ISSUE TITLE
Dynamic Desktop Overlay

### ISSUE THREAD

**Issue by mdmk** [cairoshell/cairoshell#45]
In order to access dynamic desktop, the user has to minimize everything.
A button/hotkey to show it would help to avoid this problem.
It is the contrary of #46.

@nickisghosty Could you please confirm your idea or explain further? It is you who asked for this in #33.

**Comment by dremin** [comment]
Could you please clarify? Is this request just for bringing the toolbar to the front, or the whole desktop? I am confused how this differs from #46.

**Comment by mdmk** [comment]
What I understood from @nickisghosty is he asked to be able to bring the dynamic desktop to the front. So put the shortcuts on top of other apps. It can seem a bit weird but on Windows dynamic desktop is an feature exclusive to Cairo. So it would  be a way to add flexibility to this exclusive feature.
But it could also be seen as a bug by users not aware of this feature so it is a bit dangerous to implement I think.
By the way, menu bar and task bar are visible most of the time so bringing them to top is almost never needed.
I think we should close this and wait for more feedback.

**Comment by josuave** [comment]
My recommendation for this feature, which was how I envisioned it when I originally designed and created it, was to have a global mouse hook to track when the mouse was on top of it (regardless of controls current z-order). The Dynamic Desktop controls, only those, would be moved to topmost but at  say 15-20% opacity. If the user paused on the controls for a moment or clicked then it would goto full opacity until acted on or the mouse was tracked off the controls which then it would go back to its original z-order.

Sent from my iPhone

On Jan 4, 2018, at 7:32 AM, mdmk <notifications@github.com<mailto:notifications@github.com>> wrote:


What I understood from @nickisghosty<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnickisghosty&data=02%7C01%7C%7C75f37d68190b4a005c9508d5536f3efc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636506659614298399&sdata=SZKN5v0jEMAeTVuVWDQz9RgHvYG0TJGC5hlHYt%2FvrWk%3D&reserved=0> is he asked to be able to bring the dynamic desktop to the front. So put the shortcuts on top of other apps. It can seem a bit weird but on Windows dynamic desktop is an feature exclusive to Cairo. So it would be a way to add flexibility to this exclusive feature.
But it could also be seen as a bug by users not aware of this feature so it is a bit dangerous to implement I think.
By the way, menu bar and task bar are visible most of the time so bringing them to top is almost never needed.
I think we should close this and wait for more feedback.

**Comment by dremin** [comment]
@josuave - welcome back! Are you saying even when windows are covering the controls, if the mouse cursor is at the same coordinates as the controls, the controls would come to the front?

**Comment by josuave** [comment]
That was correct. I thought about it a bunch years and thought it was a good idea but hinking about it now I think that it could be too intrusive for users. An optional setting for the mouse over, maybe? A global keyboard hook would be useful. Maybe a designated button on the “taskbar”?

Sent from my iPhone

On Jan 4, 2018, at 6:50 PM, Sam Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


@josuave<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjosuave&data=02%7C01%7C%7C131387fc897c455038a908d553cde54a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636507066127874178&sdata=q9kShNQh%2FLVCJ5yZlpcMv7Y3DeuKketYJn6v%2FV%2F5nsc%3D&reserved=0> - welcome back! Are you saying even when windows are covering the controls, if the mouse cursor is at the same coordinates as the controls, the controls would come to the front?

**Comment by dremin** [comment]
@josuave I agree that it would probably not be ideal; I would find it annoying personally, and since the controls can be moved, the user may not know where they are until they are found accidentally.

I think a button and a keyboard shortcut would be ideal activation methods for now. I was considering a button on the desktop itself, but that would only be feasible with the 'taskbar reserves space' option selected. A taskbar button would work around that, but it is possible to configure Cairo to enable Dynamic Desktop but not enable the taskbar, so then the button would become unavailable as well. Another option is on the menu bar, but I don't think we should have a significant number of icons up there, so each addition must be with care.

Regardless, I really like this idea of a dynamic desktop overlay. It would really expand the usage of the dynamic desktop to replace basic Explorer browsing tasks.

**Comment by josuave** [comment]
I spent 20-30 min the other night looking at Cairo. The moving controls was actually a surprise to me, I didn’t  know. I’m going to start playing with a plug-in system and an object model system for Cairo, both were in my original plans for it but any ways I can up with a really interesting solution.
With the controls movable a keyboard shortcut (maybe start thinking of having a shortcut assignment settings area!!!!) would work awesome but I would also include a sliver of a button on the left side of the “taskbar” that shows it. The really cool idea that I though of yesterday while I was dragging the controls around was to allow them to dock to that left side of the “taskbar” but slide back into the “taskbar” and have the same sliver button show and hide them

Sent from my iPhone

On Jan 6, 2018, at 1:14 AM, Sam Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


@josuave<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjosuave&data=02%7C01%7C%7Ca88daf5f32a4431d338508d554cccac5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636508160897621909&sdata=MC6S22xEC%2FGKePcCP52HeBGmKZyR0w6ww5%2F%2B6h8Tz%2BA%3D&reserved=0> I agree that it would probably not be ideal; I would find it annoying personally, and since the controls can be moved, the user may not know where they are until they are found accidentally.

I think a button and a keyboard shortcut would be ideal activation methods for now. I was considering a button on the desktop itself, but that would only be feasible with the 'taskbar reserves space' option selected. A taskbar button would work around that, but it is possible to configure Cairo to enable Dynamic Desktop but not enable the taskbar, so then the button would become unavailable as well. Another option is on the menu bar, but I don't think we should have a significant number of icons up there, so each addition must be with care.

Regardless, I really like this idea of a dynamic desktop overlay. It would really expand the usage of the dynamic desktop to replace basic Explorer browsing tasks.

**Comment by dremin** [comment]
I've been slowly refactoring pieces of Cairo to be more flexible, so this is good to hear. Let me know if you'd like to continue talking about this outside of the thread; there's a lot of cool stuff we will be able to do if you'd like to continue helping out!

**Comment by josuave** [comment]
Let’s do it

Sent from my iPhone

On Jan 6, 2018, at 12:02 PM, Sam Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


I've been slowly refactoring pieces of Cairo to be more flexible, so this is good to hear. Let me know if you'd like to continue talking about this outside of the thread; there's a lot of cool stuff we will be able to do if you'd like to continue helping out!

**Comment by dremin** [comment]
If you have twitter, tweet me @dremin, otherwise if you have a preferred messaging service we can use that

**Comment by dremin** [comment]
I've added a Win+Shift+D shortcut to activate the dynamic desktop overlay.

**Comment by dremin** [comment]
For UI implementation I have added a toggle button to the left side of the taskbar.
![screen shot 2018-02-01 at 12 58 09 am](https://user-images.githubusercontent.com/7373633/35663390-041144fc-06eb-11e8-844c-a3834ab4b484.png)

**Comment by dremin** [comment]
This is now available in the latest build.
