### ISSUE TITLE
Origin Client - Taskbar Icon not responsible

### ISSUE THREAD

**Issue by stinger2k** [cairoshell/cairoshell#517]

**Comment by josuave** [comment]
Do you mean responsive? In the future, it is best to use the issue template when submitting issues/bugs.
Are you referring to an icon in the quick-launch, taskbar or system tray? What version of windows are you running and is Cairo running as shell or on-top of Explorer?

Please remember, with any sort of problem solving, more information is almost always better.

**Describe the bug**
Origin Client - Taskbar Icon not responsible 

**Steps to reproduce**
1. 
2. 
3. 

**Expected behavior**
A clear and concise description of what you expected to happen.

**System information:**
 - Windows version: 
 - Cairo version: 
 - 32-bit or 64-bit: 
 - In Cairo Settings > Advanced, is Cairo set as shell?: 

**Additional context**
Add any other context about the problem here.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Comment by stinger2k** [comment]
Wrote it in Issues/Bugs…
It´s on both Shell or on top of Explorer.
The Icon in System-Tray of Cairo has no Right-click menu as it is in Explorer Shell.
I´m using Windows Pro x64 20H2 (Build 19042.685) with Cairo-Desktop 64bit

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Joe<mailto:notifications@github.com>
Gesendet: Sonntag, 10. Jänner 2021 15:32
An: cairoshell/cairoshell<mailto:cairoshell@noreply.github.com>
Cc: stinger2k<mailto:stinger2k@msn.com>; Author<mailto:author@noreply.github.com>
Betreff: Re: [cairoshell/cairoshell] Origin Client - Taskbar Icon not responsible (#517)


Do you mean responsive? In the future, it is best to use the issue template when submitting issues/bugs.
Are you referring to an icon in the quick-launch, taskbar or system tray? What version of windows are you running and is Cairo running as shell or on-top of Explorer?

Please remember, with any sort of problem solving, more information is almost always better.

Describe the bug
Origin Client - Taskbar Icon not responsible

Steps to reproduce
1.
2.
3.

Expected behavior
A clear and concise description of what you expected to happen.

System information:

  *   Windows version:
  *   Cairo version:
  *   32-bit or 64-bit:
  *   In Cairo Settings > Advanced, is Cairo set as shell?:

Additional context
Add any other context about the problem here.

Screenshots
If applicable, add screenshots to help explain your problem.

**Comment by dremin** [comment]
Thanks for the report! I am able to reproduce this.

**Comment by dremin** [comment]
This is fixed in the latest release.
