### ISSUE TITLE
Windows 7 and up like taskbar grouping

### ISSUE THREAD

**Issue by hello-wahyu** [cairoshell/cairoshell#52]

**Comment by dremin** [comment]
Regarding grouping, the method Cairo uses I mentioned in #53. However, thumbnails are a great idea!

**Comment by dragonfirecmv** [comment]
I know, but it would be nice to have that options too, besides The Windows 7 taskbar has been praised by many of its users, also flexibility :)

**Comment by dremin** [comment]
Here are my notes from previous brainstorming on the combined quick launch + task list implementation.

For categorizing windows by app:
- Windows 7 and up use AppUserModelID (AUMID) to uniquely identify applications on the system. This is required to properly categorize windows by application. Cairo already gets the explicit AUMID for apps, but not yet the implicit AUMID assigned to apps that don't explicitly define one. It may make sense to implement this in [ManagedShell.WindowsTasks.ApplicationWindow](https://github.com/cairoshell/ManagedShell/blob/master/src/ManagedShell.WindowsTasks/ApplicationWindow.cs#L43). Getting it on Windows 7 requires injection into the process and calling GetCurrentProcessExplicitAppUserModelID, which sounds unsavory. [This Win32 API can be used to get it on Windows 8 and up.](https://www.pinvoke.net/default.aspx/kernel32/GetApplicationUserModelId.html)
- A new TaskCategoryProvider will need to be created for categorizing taskbar windows by app. The App Grabber category-based TaskCategoryProvider implementation [is here](https://github.com/cairoshell/cairoshell/blob/master/Cairo%20Desktop/CairoDesktop.AppGrabber/TaskCategoryProvider.cs) as an example.
- A setting needs to be created for [switching between](https://github.com/cairoshell/cairoshell/blob/master/Cairo%20Desktop/Cairo%20Desktop/Taskbar.xaml.cs#L84) the TaskCategoryProviders.
- This can be implemented independently from the combined list below.

For combining taskbar windows with quick launch icons:
- I haven't thought this through completely yet, so the following are high-level thoughts of a potential way forward.
- Quick launch, task list, and combined quick launch + task list should all likely be separate controls, to mesh with future customization plans.
- The controls used in the taskbar need to be configurable by a separate setting.
- A data model is needed for the combined quick launch (ApplicationInfo objects from AppGrabber) and task list (ApplicationWindow objects from ManagedShell.WindowsTasks) collection.
- ApplicationInfo and ApplicationWindow objects will need a way to relate to each other. Is there a way to get the AUMID for the non-UWP apps stored in AppGrabber?
- The new combined quick launch+task list control will need to use the new data model as its data source and display a QuickLaunchButton or a TaskButton depending on the item.
- The new control will need to show a single taskbar item for a category, with the individual windows listed in the TaskThumbWindow.
- TaskThumbWindow needs to be refactored so that it can show multiple windows.

**Comment by dremin** [comment]
Available in the latest release!
