### ISSUE TITLE
Post to the Winget

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [cairoshell/cairoshell#677]
**Is your feature request related to a problem? Please describe.**
we could not setup and update cairoshell by winget now
**Describe the solution you'd like**
Post cairoshell to the [Winget List](https://github.com/microsoft/winget-pkgs)

**Describe alternatives you've considered**
Add a auto download program to the Winget which could download the true version of cairoshell

**Additional context**
`winget install cairoshell`
`winget upgrade cairoshell`

**Comment by monster1612** [comment]
there seem to be a couple different options for making this happen:

- the Cairo development team could potentially leverage [wingetcreate](https://github.com/microsoft/winget-create#using-windows-package-manager-manifest-creator-in-a-cicd-pipeline) as part of the CI/CD process for GitHub releases to automatically submit builds to the public-facing winget repos (but there's likely a delay because of human review).
- if the CI/CD integration is infeasible, anyone can [create a request](https://github.com/microsoft/winget-pkgs/issues/new/choose) for Cairo to be included in the winget repo, but this would likely need to be done every time Cairo gets an update.

**Comment by josuave** [comment]
@dremin do you think we can add, to the ci/cd pipeline, the ability to update the required info and submit a pr to the winget repo

**Comment by xoascf** [comment]
@dremin, there is a way to do this without using or relying on other GitHub Actions created by other people.
You can read how it works: https://www.techwatching.dev/posts/wingetcreate
