### ISSUE TITLE
Win + D shortcut

### ISSUE THREAD

**Issue by mdmk** [cairoshell/cairoshell#73]
Win + D shortcut should not toggle dynamic desktop in addition to toggling windows (minimize/restore).

**Comment by pmikstacki** [comment]
Win+D is an explorer.exe registered key. We need to override this hotkey with p/invoke (I can find a solution) or write a new explorer app from scratch (xD)

**Comment by josuave** [comment]
Are you running on top of Explorer shell or is Cairo the shell?

Sent from my iPhone

On Jan 13, 2018, at 7:40 AM, theepicmixer <notifications@github.com<mailto:notifications@github.com>> wrote:


Win+D is an explorer.exe registered key. We need to override this hotkey with p/invoke (I can find a solution) or write a new explorer app from scratch (xD)

**Comment by pmikstacki** [comment]
isn't the explorer neccesary to run with uwp-host functionality? I was developing something similair and uwp apps won't start without explorer

**Comment by dremin** [comment]
@pmikstacki Yes, Explorer needs to be running for UWP apps to function.

**Comment by dremin** [comment]
When WinKey+D is used, a shell WorkerW window is made the topmost window covering all windows. The referenced commit works around this by making the Cairo Desktop window topmost once the WorkerW window becomes topmost.

**Comment by dremin** [comment]
This is resolved in the latest build.

**Comment by dremin** [comment]
Reopening this because I am going to revert the change as it has too many problems.

**Comment by dremin** [comment]
It doesn't look like I can override Win+D since it is already registered by Explorer. #45 will fix this with the Win+Shift+D shortcut.

**Comment by josuave** [comment]
I don’t have my computer near me but see if this allows you to override the win+d combo:

In registry:

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer

create a new DWORD NoWinKeys and set its value to 1

This should disable all win key combos. I have not tested but I would imagine that it just tells explorer not to register them.

Sent from my iPhone

On Jan 28, 2018, at 1:52 AM, Sam Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


It doesn't look like I can override Win+D since it is already registered by Explorer. #45<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcairoshell%2Fcairoshell%2Fissues%2F45&data=02%7C01%7C%7C40eb6c203bf3433fd19d08d5661bae93%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636527191429848435&sdata=FCTen%2FcWWCIlqzOxh%2FMUxxqTEkZMR7BYr0jcEXZMRXw%3D&reserved=0> will fix this with the Win+Shift+D shortcut.

**Comment by dremin** [comment]
This works, but it removes the ability for Cairo to invoke Action Center (there used to be a URI to access it but this was removed). It also removes the Run shortcut but this is easily fixed by adding a shortcut in Cairo. Surprisingly Task View still works (Win-Tab) and the Snap commands.

**Comment by josuave** [comment]
Very interesting, I assumed that that all would break.

Sent from my iPhone

On Jan 28, 2018, at 3:56 PM, Sam Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


This works, but it removes the ability for Cairo to invoke Action Center (there used to be a URI to access it but this was removed). It also removes the Run shortcut but this is easily fixed by adding a shortcut in Cairo. Surprisingly Task View still works (Win-Tab) and the Snap commands.

**Comment by dremin** [comment]
I'll make the hotkey customizable so that if a user prefers to enable the registry value, they can change Cairo to use Win+D.

**Comment by dremin** [comment]
Hotkey customization plus the registry trick above seems to solve this; closing.

**Comment by beppe9000** [comment]
I am experiencing this.
