### ISSUE TITLE
Start Cairo when logging in option adds "CairoDesktop.dll" to the startup apps list instead of "CairoDesktop.exe"

### ISSUE THREAD

**Issue by hkdemiralp** [cairoshell/cairoshell#857]
**Describe the bug**
Cairo Shell does not start on login. It asks which app to open "cairoshell.dll" file.  The option "Start Cairo when logging in" adds "CairoDesktop.dll" to the startup apps list instead of "CairoDesktop.exe". If I run the Cairo Desktop app from start menu it works fine.
**Steps to reproduce**
1. Enable "Start Cairo when logging in" in Caire Shell settings.
2. Restart computer.
3. Cairo shell is not started. Instead ask which app to open cairoshell.dll file.

**Expected behavior**
After enabling "Start Cairo when logging in" option in Caire Shell settings, Cairo Shell should start at login.

**System information:**
 - Windows version: Windows 11 Pro 23H2, OS Build: 22631.4249
 - Cairo version: 0.4.370.35207
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?:  No

**Additional context**
I think the option "Start Cairo when logging in" should add "CairoDesktop.exe" to the startup apps list instead of "CairoDesktop.dll".
I uninstalled Cairo Shell and reinstalled but nothing changed.
Also I install Cairo Shell with Chocolatey package manager.

**Comment by ivan8994** [comment]
`

> should add "CairoDesktop.exe" to the startup apps list instead of "CairoDesktop.exe".

`
1) cairo.exe instead of cairo.exe ? 

2) I also have this enabled "start on log in" but it always starts as expected . 
also I additionally checked startup folder and it has no links in it, probably it starts by some other method. 
I use cairo same version as you, and also not use cairo as default shell. 
in my autorun settings i checked the file of Cairo and it seems like C:\Program Files\Cairo Shell\CairoDesktop.exe . 
so I have exe not dll. but I use Windows 10 22H2.  
check your path of Cairo maybe ? if this same , probably due to W11 new updates something changed again and Cairo cant do job as it is supposed to do.

**Comment by hkdemiralp** [comment]
> > should add "CairoDesktop.exe" to the startup apps list instead of "CairoDesktop.exe".
> 
>     1. cairo.exe instead of cairo.exe ?
> 
Hi, Ivan. I corrected my typo, sorry. I mean the entry "CairoDesktop Environment" in task manager on the startup apps tab links to the "CairoDesktop.dll" file.
In Cairo settings, "Start cairo when logging in" option adds the following registry entry:
```
Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run
Value: CairoShell
Value data: C:\Program Files\Cairo Shell\CairoDesktop.dll
```

It is strange to have a "dll" file on startup list. I don't think I have ever seen any other "dll" file there, before.

**Comment by dremin** [comment]
Oops! I'll get this fixed.

**Comment by hkdemiralp** [comment]
This bug reappeared.
Cairoshell version: Version 0.4.370.35207 - Pre-release

**Comment by dremin** [comment]
@hkdemiralp The issue was fixed in the code but we haven't made any releases yet with the fix. However, you can download the newest dev version [here](https://github.com/cairoshell/cairoshell/actions/runs/12688779418/artifacts/2406601379) and it should be fixed in that one. You'll need to remove the bad CairoDesktop.dll startup item if it got added back.

**Comment by hkdemiralp** [comment]
Thanks. The dev version works great. Sorry for my confusion.
Best wishes.
